import type { Metadata } from "next";
import {  Barlow_Condensed, Inter, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import "@fortawesome/fontawesome-svg-core/styles.css";


// const inter = Inter({ subsets: ["latin"] });
// const barlow = Barlow_Condensed({
//   subsets: ["latin"],
//   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
//   variable: '--font-barlow',
// });
const jakarta = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={` ${jakarta.className}`}>
        {/* <Navbar /> */}
        {/* <div className="bg-wibu-400 min-h-screen">{children}</div> */}
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
